apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/rook/rook/blame/v1.6.2/cluster/examples/kubernetes/ceph/crds.yaml
- https://github.com/rook/rook/blame/v1.6.2/cluster/examples/kubernetes/ceph/common.yaml
- https://github.com/rook/rook/blame/v1.6.2/cluster/examples/kubernetes/ceph/operator.yaml
- https://github.com/rook/rook/blame/v1.6.2/cluster/examples/kubernetes/ceph/cluster.yaml
- https://raw.githubusercontent.com/rook/rook/v1.6.2/cluster/examples/kubernetes/ceph/csi/rbd/storageclass.yaml
- ingress.yaml
