apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/rook/rook/v1.7.7/cluster/examples/kubernetes/ceph/crds.yaml
- https://raw.githubusercontent.com/rook/rook/v1.7.7/cluster/examples/kubernetes/ceph/common.yaml
- https://raw.githubusercontent.com/rook/rook/v1.7.7/cluster/examples/kubernetes/ceph/operator.yaml
- https://raw.githubusercontent.com/rook/rook/v1.7.7/cluster/examples/kubernetes/ceph/cluster.yaml
- https://raw.githubusercontent.com/rook/rook/v1.7.7/cluster/examples/kubernetes/ceph/toolbox.yaml
- https://raw.githubusercontent.com/rook/rook/v1.7.7/cluster/examples/kubernetes/ceph/csi/rbd/storageclass.yaml
- https://raw.githubusercontent.com/rook/rook/v1.7.7/cluster/examples/kubernetes/ceph/monitoring/rbac.yaml
- ingress.yaml
- objectstorage.yaml
patchesStrategicMerge:
- patch-cephcluster.yaml
