apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-prometheus
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 13.8.0
    helm:
      values: |
        server:
          persistentVolume:
            storageClass: "rook-ceph-block"
          statefulSet:
            enabled: true
        alertmanager:
            enabled: false
