apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
spec:
  encryptedData:
    secretkey: AgALvFwo2NAr6QSC4LdduZqHU4lq1RFdcyTU+YUx5GN4eLSwUbRyO3jWUAfd8rO/8qlDhtLi65xMkzF40IDB3anNDbyf6ad8nvuM9eTgOT6g3VzgJDOr+oy1wf1VBVmPL4cpsDt4+qw4Wog6Wv6N8LR2bHkYH25DlJIeNmIw2d1X/YO9V4EnMZOWPMENFyQBgDrFm3Cs7CUyPyDa+UPaQepI4aw2AW6qzveFZ/uIbNZNn97rsPHWFdX4d4ESS0X8dFq1MmTPbgAweSn7MDrvPeuINcGJI4V+NbjpXiMBFdIGTW1EO7IncVjwLFYxn2/oBAdA4p+ALnQiURxZap6uzwBteIoQGF4AKFRLX5gxjKX9QKtAo+gqGONDp2GIqjaWH8OLHNpWNTP053o9+1LNZj7UtL18xxrxcn/iTdU5HPIUhD/0phS1XpeQTHyt8bAcjIzVEy4Z2rs4kavwsS8shB/0hXVQyKfyCAFhUI83IArklc6Gq0zkhAzXMlPAj/OKUdEHp/Qhpwggt2W+F+F1CaRhn7MwJ2lmdtzNZxOHcnQSrCMEHdsnKYYwM8/OY7Slnj+DRLgNw6PA11hnaIUv5kCfHdEHV6SuECWKWPLb9NZh6ryr+xSTHgFZgSoJ22e+1zy9EYrpd9ab76UIN6FIremvFl15HAf5pHj2/8jbMMWuDkBJeCgEfWx0qFG9lEpUo5M5uWO3U4/Dd5o4VtcXXK3DNPXGNR8YUdIoiw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: memberlist
      namespace: metallb-system

