apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCmus8iG+8e14NzDjzj4pD7yFBIvgTNK/qTsLqlql1BtoFw0/nN3QCO0S6j5mW047EHvTvD36yw3X8RiW565pWqSRdcfLN7d4j5FTeKY0T05XucH+avCSR5PsDjobhEHkoOikaiyJ0ZwGhCIE5Yhpfoq+6nvJI8fw5vO+LNQx/l7eT6LmO9te5k5ORdTfv5iyupe2ihQDDc+wpxI9p3k3H7NrD/JHBYDqbfbzC6jmOr4euVrNyFpu3suZvdv2RxJ4XrTYeEOhUIZTL2gIjRYHeH0V1QDUsGXMOWfups1mgXroF/FvlUzhmllhg9F95m0XvbFW5FPe1xLQxsfNx3s5uiHSzC7/1zsth7Xp3B9sbeqM7eCjzqZzb7Rm/d4DJgB0cSDk3NvpsP0sQExJeVSjkcF8VNmf33tij52F3t6ja0pGbI74ZRKvvaFt36xTO3HejZXb6gYhISFvbMs+E0+RQMBUG7a0vsj4J1JBIqqKWNKlAkSgHyiY1XDUIiZpUT1L8wQ8Gcqox32KyKEXGrveSAhYJwKNcZhyRPZQLnm32uJf1ZWArG36hooFHcbQ4lYLfGOCZwZ9K+tBeg55ytwi9KOAlQP4CX6Q90E1Gw9Yyav0D02MjXTISDjCackG1GrhpUvVac0thWVCf1MXiSFvUtRrbMs1e3ok6qbFrKBbKcGhw/n5pGpfuvfCg7lIuJGTBNsPvtEXjPEjwd+hBrDFgQx4kNEIvopB25bgWh7BOOq7RYpSkUgxst
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager

